spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: homer_forever
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true