spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: homer_forever
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true