drop table if exists person;

create table person (
    id int primary key generated by default as identity,
    username varchar(100) not null,
    birth_year int not null,
    password varchar not null
);
