drop table if exists person;

create table person (
    id int primary key generated by default as identity,
    username varchar(100) not null,
    birth_year int not null,
    password varchar not null
);


drop table if exists authorities;
drop table if exists users;

create table users (
    username varchar(255) not null primary key,
    password varchar(255) not null,
    enabled boolean not null
);

create table authorities (
    username varchar(255) not null,
    authority varchar(255) not null,
    foreign key (username) references users (username),
    unique (username, authority)
);